function (setup_mpir arg_libdir arg_libname)
  get_platform_depended_library_path(LIB_PATH_PART)
  set(${arg_libname} mpir PARENT_SCOPE)
  set(${arg_libdir} ${PROJECT_BINARY_DIR}/third_patry/mpfr_gmp_mpir/mpir/$<CONFIG> PARENT_SCOPE)
endfunction (setup_mpir)

function (setup_gmp arg_libdir arg_libname)
  get_platform_depended_library_path(LIB_PATH_PART)
  set(${arg_libname} gmp PARENT_SCOPE)
  set(${arg_libdir} ${GLOBALIZER_OUTPUT_DIRECTORY} PARENT_SCOPE)
endfunction (setup_gmp)

function (setup_mpfr arg_libdir arg_libname)
  get_platform_depended_library_path(LIB_PATH_PART)
  set(${arg_libname} mpfr PARENT_SCOPE)
  set(${arg_libdir} ${PROJECT_BINARY_DIR}/third_patry/mpfr_gmp_mpir/mpfr/$<CONFIG> PARENT_SCOPE)
endfunction (setup_mpfr)